# Generated by Django 4.0.6 on 2022-09-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
