# Generated by Django 4.0.6 on 2022-10-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_postcomments_date_created_siteuser_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='profile_pic',
            field=models.ImageField(default='avatar.jpg', upload_to='profile_pics'),
        ),
    ]
