# Generated by Django 4.0.6 on 2022-10-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_siteuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='nationality',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
