# Generated by Django 4.0.6 on 2022-10-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_siteuser_gender_alter_siteuser_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remote', 'Remote')], default='Others', max_length=20),
        ),
    ]
