# Generated by Django 4.0.6 on 2022-11-03 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_jobapplication_job_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.CharField(default='Kampala', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.job'),
            preserve_default=False,
        ),
    ]
