# Generated by Django 4.0.6 on 2022-11-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
