# Generated by Django 4.0.6 on 2022-11-22 20:18

import core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_job_category_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(upload_to='cvs', validators=[core.validators.cv_validator]),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='nationality',
            field=django_countries.fields.CountryField(default='Kenya', max_length=2),
            preserve_default=False,
        ),
    ]
