# Generated by Django 4.0.6 on 2022-11-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_notification_user_notification_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.URLField(default='https://docs.aws.amazon.com/assets/r/images/aws_logo_dark.png'),
        ),
    ]
