# Generated by Django 4.0.6 on 2022-11-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_siteuser_profile_pic_alter_post_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='profile_pic',
            field=models.ImageField(default='avatar.jpg', upload_to='profile_pics'),
        ),
    ]
